<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Demande de Passeport</name>
   <tag></tag>
   <elementGuidId>43335841-d163-4c2a-b7ba-2aeb05ffc644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div[2]/div/a/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-5.grow.flex.flex-col.justify-between</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26328a9d-b172-4fd8-a713-59d9cea71815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-5 grow flex flex-col justify-between</value>
      <webElementGuid>fcf0a12d-7d5e-44c9-b275-6542e9698241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demande de Passeport pour la Mobilité de la Formation Professionnelle</value>
      <webElementGuid>f2c1a7d2-78c7-4fcd-88c1-74fda9655c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;flex flex-col gap-2 px-4 mx-auto max-w-7xl&quot;]/div[@class=&quot;grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 justify-items-center my-4 mx-2 md:mx-0&quot;]/a[@class=&quot;w-full&quot;]/div[@class=&quot;h-full bg-white flex flex-col border border-gray-200 hover:bg-gray-100&quot;]/div[@class=&quot;p-5 grow flex flex-col justify-between&quot;]</value>
      <webElementGuid>f41f239e-c63c-4844-bde9-83f499ca8fe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/a/div/div</value>
      <webElementGuid>b30be6a4-96d1-4f22-b077-cb1acd1eee1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toutes les aides'])[1]/following::div[3]</value>
      <webElementGuid>f11cb7f3-2f91-4d06-818d-9e5027ad8abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bienvenue sur le portail LADOM'])[1]/following::div[4]</value>
      <webElementGuid>0b9a8026-e97f-49d5-bc75-dc7df859a930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demande d’Aide aux Obsèques'])[1]/preceding::div[2]</value>
      <webElementGuid>061116bb-9ddb-4610-ad86-8edbab4db036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>f3a9ffd3-4a02-4381-9342-7320e8a43f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Demande de Passeport pour la Mobilité de la Formation Professionnelle' or . = 'Demande de Passeport pour la Mobilité de la Formation Professionnelle')]</value>
      <webElementGuid>714a87d8-1203-4fab-b325-18e5a37d4911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
