<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_unionEuropeene</name>
   <tag></tag>
   <elementGuidId>580cea71-ab61-4bb0-8ad8-a020ed506707</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ml-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Plan du site'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d343015-de23-4404-927e-50e316ef42d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ladom.fr/lunion-europeenne</value>
      <webElementGuid>7199397c-54ec-4ab6-a252-e0d38df85cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-8</value>
      <webElementGuid>5b0b2e61-d0d2-4186-adce-d696bae19058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0f6e1a3f-a1b8-40c8-bc57-1a137ee126da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[@class=&quot;bg-[#f2f2f2] py-12&quot;]/div[@class=&quot;px-4&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 items-center py-6&quot;]/div[@class=&quot;grid grid-cols-2 mb-4&quot;]/a[@class=&quot;ml-8&quot;]</value>
      <webElementGuid>2d0255c9-2915-4de8-9c5a-05257f92731d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plan du site'])[1]/following::a[1]</value>
      <webElementGuid>ad87e1fa-9e45-4766-82bf-d2f6ddfa0686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registre des actes administratifs'])[1]/following::a[2]</value>
      <webElementGuid>07eb5f54-7d0e-43e3-93ec-a051ea690575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v1.2.3 - © LADOM 2024'])[1]/preceding::a[6]</value>
      <webElementGuid>d7f961fe-135b-44ac-b8e0-ffe647eb8545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://ladom.fr/lunion-europeenne')])[3]</value>
      <webElementGuid>43d3ec16-00d9-4f57-880f-ce1d20967a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[2]/div/a</value>
      <webElementGuid>dbea0a1a-98af-4ce2-81f3-0d574edeb6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ladom.fr/lunion-europeenne']</value>
      <webElementGuid>9885c6e9-29fd-4fd5-9007-16ef96558e72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
