<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_facebook</name>
   <tag></tag>
   <elementGuidId>206fdcf5-6567-4914-b6af-6ce86ccd44ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ml-8 > img[title=&quot;facebook_header&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@title='facebook_header'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4a613e59-c538-4f6d-9117-f89fc662a1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>facebook_header</value>
      <webElementGuid>fade0c85-80c2-4f5c-ac87-02a8b1993eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/social/facebook_header.svg</value>
      <webElementGuid>28165bba-218c-4829-8887-4fadf954dbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[@class=&quot;bg-[#f2f2f2] py-12&quot;]/div[@class=&quot;px-4&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 items-center py-6&quot;]/div[@class=&quot;flex items-center justify-around md:justify-end&quot;]/a[@class=&quot;ml-8&quot;]/img[1]</value>
      <webElementGuid>11c10108-7a43-48cd-b6b9-545f7c401454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='facebook_header'])[2]</value>
      <webElementGuid>b684fc61-158c-40d4-9f78-ad1650f32bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]/img</value>
      <webElementGuid>3539cbed-ea13-49bc-af2f-67462c9682fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'facebook_header' and @src = '/social/facebook_header.svg']</value>
      <webElementGuid>ad0b2bfe-cfb4-425c-8429-6de2b34e65a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
