<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Funeraire</name>
   <tag></tag>
   <elementGuidId>66f4a4d4-ef3f-43ad-9613-dedc7b73a975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Urgences de la vie'])[2]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Funéraire &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>97a749fc-e27e-4e71-9f9e-6983c80ce0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ladom.fr/urgences-de-la-vie/funeraire/</value>
      <webElementGuid>2daf7d31-7cf8-4cbd-9dd8-24fb067ec8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Funéraire</value>
      <webElementGuid>61fd98ba-c18d-437d-98b4-51e412bde546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between text-lg leading-6 pb-2 border-b border-transparent hover:border-white</value>
      <webElementGuid>4d0ddf4b-9481-4ba2-9eff-5a24c9c9b5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Funéraire</value>
      <webElementGuid>5a86a9b6-2a57-4443-9eb3-e1a74bdcf6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;hidden lg:flex justify-end items-center flew-row w-full relative px-4 py-6 mb-4&quot;]/div[@class=&quot;group&quot;]/div[@class=&quot;hidden group-hover:flex bg-ladom-prune text-white absolute top-16 left-0 right-0 py-12 z-10 mx-4&quot;]/div[@class=&quot;w-1/4 flex flex-col&quot;]/div[@class=&quot;py-2 me-8&quot;]/a[@class=&quot;flex justify-between text-lg leading-6 pb-2 border-b border-transparent hover:border-white&quot;]</value>
      <webElementGuid>a946eeee-83bd-4a76-a222-3fb3547b5832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urgences de la vie'])[2]/following::a[1]</value>
      <webElementGuid>e7c7cc13-13df-4894-af85-e964aaf9c557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aide au voyage Talents'])[1]/following::a[2]</value>
      <webElementGuid>f4fb3a80-87d5-478b-8a05-fa9255a797fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enfants évacués sanitaires'])[1]/preceding::a[1]</value>
      <webElementGuid>f8d9f346-f455-4cf9-92d4-9efcffeef85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ladom.fr/urgences-de-la-vie/funeraire/')]</value>
      <webElementGuid>2039b3f9-f73a-4e65-bac2-d10f065d76da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/a</value>
      <webElementGuid>ba34bc2f-1b0c-4474-ae1c-f8d5e4a60639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ladom.fr/urgences-de-la-vie/funeraire/' and @title = 'Funéraire' and (text() = 'Funéraire' or . = 'Funéraire')]</value>
      <webElementGuid>dbb75a71-dfe1-4aa0-a1e3-00e3f795c2a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
