<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>facebook</name>
   <tag></tag>
   <elementGuidId>1581457c-1cda-4ba7-a146-d794463ef44e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@title='facebook_header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[title=&quot;facebook_header&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0bbdf9b-da2f-4f3d-8500-b3ce1e515d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>facebook_header</value>
      <webElementGuid>212a10d0-6dca-4f3a-a3a0-dd8d197334f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/social/facebook_header.svg</value>
      <webElementGuid>4a91480b-cd7f-439a-957b-de6d1afd5f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;w-full flex justify-between items-center pt-4 px-4&quot;]/div[@class=&quot;flex justify-end items-center&quot;]/div[@class=&quot;hidden md:flex ml-4 lg:ml-0&quot;]/a[@class=&quot;ml-2&quot;]/img[1]</value>
      <webElementGuid>c0096271-6934-4101-ab1c-51a5e2cd799c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='facebook_header']</value>
      <webElementGuid>7ed00e7e-f2e3-48dc-9abb-4ca3444ba95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>abceee3c-169c-4e59-b907-ab4d827ad501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'facebook_header' and @src = '/social/facebook_header.svg']</value>
      <webElementGuid>81563fb1-7b4c-4653-b55d-19a35e05fb0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
