<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>instagram</name>
   <tag></tag>
   <elementGuidId>9d7e69d7-9fb6-408b-9a59-5d25c98f937f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@title='instagram_header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[title=&quot;instagram_header&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b59a636a-5353-4b01-a445-fef6c30fb28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>instagram_header</value>
      <webElementGuid>6771fb88-1966-461d-88c9-8dfa8c0b805a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/social/instagram_header.svg</value>
      <webElementGuid>3798d3b6-97ab-4d5b-a79b-5f3cf58b0bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;w-full flex justify-between items-center pt-4 px-4&quot;]/div[@class=&quot;flex justify-end items-center&quot;]/div[@class=&quot;hidden md:flex ml-4 lg:ml-0&quot;]/a[@class=&quot;ml-2&quot;]/img[1]</value>
      <webElementGuid>228be4d5-dfdf-4bca-bdce-60d196b302a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='instagram_header']</value>
      <webElementGuid>475921c3-ce93-40cd-b33a-e588dec112cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>4dbfd51d-24f1-4751-9371-c1e05b02e794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'instagram_header' and @src = '/social/instagram_header.svg']</value>
      <webElementGuid>0fca7398-f8d9-4458-8bbb-91200e9e794f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
