<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>twitter</name>
   <tag></tag>
   <elementGuidId>b7c6f95a-78d8-42dc-bf00-1781d5f2960e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@title='linkedin_header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[title=&quot;linkedin_header&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>892fc17b-7beb-4260-9d4e-03d42b83f110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>linkedin_header</value>
      <webElementGuid>eb32146d-4674-4ec7-ad3c-edf5f8a0be39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/social/linkedin_header.svg</value>
      <webElementGuid>4c92dd4d-db99-4b1a-84a9-43312924e239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;w-full flex justify-between items-center pt-4 px-4&quot;]/div[@class=&quot;flex justify-end items-center&quot;]/div[@class=&quot;hidden md:flex ml-4 lg:ml-0&quot;]/a[@class=&quot;ml-2&quot;]/img[1]</value>
      <webElementGuid>3e4b5073-6aea-4a44-a1f9-8a2df78bfb06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='linkedin_header']</value>
      <webElementGuid>c450091f-c95e-4fcb-b0b4-8d7b73c90a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/img</value>
      <webElementGuid>5ea5e22f-8e26-4b17-9570-4fd1e7e836fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'linkedin_header' and @src = '/social/linkedin_header.svg']</value>
      <webElementGuid>f9c66b77-47cf-4f75-a32b-180c57d141a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
