<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Je menregistre</name>
   <tag></tag>
   <elementGuidId>868d2b23-c0bb-4440-84fb-78d7663cd346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div/div[2]/a[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75e7da7e-1892-496b-a0ac-0b2eeeedc762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>min-h-32 bg-white grid grid-cols-[minmax(auto,80px)_1fr] gap-4 p-4 relative cursor-pointer hover:bg-gray-100</value>
      <webElementGuid>48e8b8f3-5356-4c46-a87c-24821394d815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Je m'enregistre</value>
      <webElementGuid>d27042dc-8dfd-4273-bb00-ff172e64a09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;px-4 mx-auto max-w-7xl&quot;]/div[@class=&quot;mx-auto py-16&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-[repeat(auto-fill,minmax(300px,1fr))] gap-6 mb-8&quot;]/a[@class=&quot;border border-gray-300 border-b-0 shadow-[0_4px_0_0_rgba(29,78,216,1)]&quot;]/div[@class=&quot;min-h-32 bg-white grid grid-cols-[minmax(auto,80px)_1fr] gap-4 p-4 relative cursor-pointer hover:bg-gray-100&quot;]</value>
      <webElementGuid>74ed08da-82f9-49d7-8c82-25ae5fe0bd43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div/div[2]/a[2]/div</value>
      <webElementGuid>1068f3a2-9fd0-4d63-a3a1-e3e97455a335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Je souhaite découvrir les dispositifs'])[1]/following::div[2]</value>
      <webElementGuid>f8c6fe01-72b3-491e-a129-38291eddf534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[2]/following::div[10]</value>
      <webElementGuid>d095b5a5-c26d-4fda-ab4c-cbfdb685cb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Je me connecte'])[1]/preceding::div[3]</value>
      <webElementGuid>ed87c4ad-3808-447b-b1b9-04664ebfaa07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div</value>
      <webElementGuid>a3a0b487-d6e5-42b6-b0d0-79575a5efe90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Je m&quot; , &quot;'&quot; , &quot;enregistre&quot;) or . = concat(&quot;Je m&quot; , &quot;'&quot; , &quot;enregistre&quot;))]</value>
      <webElementGuid>a1bb6b40-e09b-41a5-8063-8a3e44da0993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
