<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Contact_h-20 w-20 object-scale-down ove_9780fd</name>
   <tag></tag>
   <elementGuidId>fe5632e6-4c87-4c27-b21f-473866fa300d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.h-20.w-20.object-scale-down.overflow-hidden.mx-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div/div[2]/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b585c56a-7f86-4cbf-8350-0d972d33f1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/pictograms/book.svg</value>
      <webElementGuid>89df242c-9bec-45a5-b9f5-9398c769cf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-20 w-20 object-scale-down overflow-hidden mx-auto</value>
      <webElementGuid>59ad1ace-23f4-4d66-9c77-b54f6c9f8bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;px-4 mx-auto max-w-7xl&quot;]/div[@class=&quot;mx-auto py-16&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-[repeat(auto-fill,minmax(300px,1fr))] gap-6 mb-8&quot;]/a[@class=&quot;border border-gray-300 border-b-0 shadow-[0_4px_0_0_rgba(29,78,216,1)]&quot;]/div[@class=&quot;min-h-32 bg-white grid grid-cols-[minmax(auto,80px)_1fr] gap-4 p-4 relative cursor-pointer hover:bg-gray-100&quot;]/img[@class=&quot;h-20 w-20 object-scale-down overflow-hidden mx-auto&quot;]</value>
      <webElementGuid>27f34df8-d528-4b3e-a13a-7d8e3a351bb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div/div[2]/a/div/img</value>
      <webElementGuid>5781de18-7640-4ece-8643-3acf12b8b8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>b68ae6a5-4580-467a-a648-80f156a36921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/pictograms/book.svg']</value>
      <webElementGuid>2bedd0e1-f74e-4070-ae19-fa95ebddfe42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
