<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_soc_x</name>
   <tag></tag>
   <elementGuidId>d0c2d1dd-59e9-4a82-8b4b-338529219568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@title='x_header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[title=&quot;x_header&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>290c3b2a-ce6d-4924-8b92-5872d61ec7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>x_header</value>
      <webElementGuid>2d096d72-9c91-4b48-a5ad-7b8c45c4bd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/social/x_header.svg</value>
      <webElementGuid>536c76a5-c4ff-48bb-bc71-f873bddbe1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;w-full flex justify-between items-center pt-4 px-4&quot;]/div[@class=&quot;flex justify-end items-center&quot;]/div[@class=&quot;hidden md:flex ml-4 lg:ml-0&quot;]/a[@class=&quot;ml-2&quot;]/img[1]</value>
      <webElementGuid>5020498d-e572-4b75-b52f-f50a7d33f5aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='x_header']</value>
      <webElementGuid>417e834f-793c-4657-b781-8a0c63bf235a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>573c5da1-09de-47e0-accb-adfb5ebbf578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'x_header' and @src = '/social/x_header.svg']</value>
      <webElementGuid>0fe5ead0-25f6-46a3-86d3-d5b0a8e2fdba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
