<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_soc_in</name>
   <tag></tag>
   <elementGuidId>732dfb12-92bc-4ac2-af16-acbe76b66c4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@title='linkedin_header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[title=&quot;linkedin_header&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0e69a811-09f6-433e-8ef5-903d6d15c518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>linkedin_header</value>
      <webElementGuid>b2ef9d15-3730-4072-ad09-f977c6252260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/social/linkedin_header.svg</value>
      <webElementGuid>acd6b3a1-55ab-421c-b136-0f65d0d4dbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;w-full flex justify-between items-center pt-4 px-4&quot;]/div[@class=&quot;flex justify-end items-center&quot;]/div[@class=&quot;hidden md:flex ml-4 lg:ml-0&quot;]/a[@class=&quot;ml-2&quot;]/img[1]</value>
      <webElementGuid>2758f353-6211-4834-85a7-57ee2e5d40ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='linkedin_header']</value>
      <webElementGuid>8d80fd0e-ab2a-40e6-940c-d7336614afb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/img</value>
      <webElementGuid>19fdc258-b4ca-4cbc-b3a7-0df13d747e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'linkedin_header' and @src = '/social/linkedin_header.svg']</value>
      <webElementGuid>1e8a8448-e7f1-493f-ab1a-824fb6e8f855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
