<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_logo</name>
   <tag></tag>
   <elementGuidId>ed201015-dec2-4f4b-aab4-ba701decac40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Logo RF LADOM']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.max-h-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b2a2e6fb-ac43-4a5c-96e5-be6f665843e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/beneficiaire/LADOM.png</value>
      <webElementGuid>8370c295-04fa-4b5a-a3e5-e500dd95553b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo RF LADOM</value>
      <webElementGuid>8ceef5d3-fcac-426a-9492-47cfa6036744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-h-16</value>
      <webElementGuid>2af86271-86cd-4b5a-8f8a-45967be7228f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;w-full flex justify-between items-center pt-4 px-4&quot;]/div[1]/a[1]/img[@class=&quot;max-h-16&quot;]</value>
      <webElementGuid>2496d71f-b113-4ec5-8b05-d8b3f8c9de42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo RF LADOM']</value>
      <webElementGuid>b3025aaa-1bc3-47c2-8049-b2a85e7a892e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ba3d954e-a925-4515-b8df-41b7d30daa2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/beneficiaire/LADOM.png' and @alt = 'Logo RF LADOM']</value>
      <webElementGuid>b8ed4ea9-cb53-478f-a9ed-d111ccf11065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
