<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LUnion_Europenne</name>
   <tag></tag>
   <elementGuidId>4be769a4-0cf1-4b2c-bffb-717551b1fed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Espace Presse'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a9714e2-7155-45fb-83bf-d6d806d4debf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ladom.fr/lunion-europeenne/</value>
      <webElementGuid>7b869364-7b7d-4209-b899-adbb2bbf4d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-6</value>
      <webElementGuid>b79431a3-f28b-4814-ba70-0fee2eec7ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>L'Union Européenne</value>
      <webElementGuid>d84d5ff6-2fd0-4d6b-847d-339914c6933b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[@class=&quot;bg-[#f2f2f2] py-12&quot;]/div[@class=&quot;px-4&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gapx-4 border-b border-gray-400 text-gray-600 text-lg py-8&quot;]/div[@class=&quot;flex flex-col&quot;]/a[@class=&quot;mb-6&quot;]</value>
      <webElementGuid>75032176-f7ce-4a39-8240-fb7594071246</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Espace Presse'])[1]/following::a[1]</value>
      <webElementGuid>e8a8c39f-87ee-40f5-bd25-021fe01a65ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charte de Protection des données des bénéficiaires'])[1]/following::a[2]</value>
      <webElementGuid>9c687901-52d7-4d09-be0d-ff894dfa6e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marchés publics'])[1]/preceding::a[1]</value>
      <webElementGuid>c538dc52-ef51-44a6-a063-df3c272a6622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registre des actes administratifs'])[1]/preceding::a[2]</value>
      <webElementGuid>e2193b2a-9989-4d5e-a059-8cf85f2389e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://ladom.fr/lunion-europeenne/')])[2]</value>
      <webElementGuid>d10d898e-001d-4076-b579-14b91488491a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div[3]/a</value>
      <webElementGuid>6b69a2ca-46af-419e-8404-92d039bb8b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ladom.fr/lunion-europeenne/' and (text() = concat(&quot;L&quot; , &quot;'&quot; , &quot;Union Européenne&quot;) or . = concat(&quot;L&quot; , &quot;'&quot; , &quot;Union Européenne&quot;))]</value>
      <webElementGuid>bf9fbb80-b661-47d3-9161-d9bb226a866d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
