<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Entrypoint</name>
   <tag></tag>
   <elementGuidId>55328d9e-9821-4d6f-bcdd-869d1b7904c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'LADOM')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;LADOM&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3777adb8-0810-471c-92cc-6336062261be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5466bff1-d356-4a4d-9703-b1139ce4b7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-1 px-4 py-4 whitespace-nowrap border-b-[3px] border-ladom-gray group-hover:bg-ladom-gray group-hover:text-white uppercase font-bold </value>
      <webElementGuid>5b4b7cb2-1d54-4480-97a2-81e035950d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LADOM</value>
      <webElementGuid>ad5dff8e-449f-4ce4-97e9-86a4e6fb553b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;hidden lg:flex justify-end items-center flew-row w-full relative px-4 py-6 mb-4&quot;]/div[@class=&quot;group&quot;]/a[@class=&quot;mr-1 px-4 py-4 whitespace-nowrap border-b-[3px] border-ladom-gray group-hover:bg-ladom-gray group-hover:text-white uppercase font-bold&quot;]</value>
      <webElementGuid>b9bd2416-f61c-4642-8d1f-ab415d07e093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LADOM')]</value>
      <webElementGuid>8d9a66d8-56db-460c-bf93-e76de051b945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enfants évacués sanitaires'])[1]/following::a[1]</value>
      <webElementGuid>a1d48d68-edf5-4f7f-95ad-dafc35e5fca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funéraire'])[1]/following::a[2]</value>
      <webElementGuid>e2b6582c-7125-4b5c-a675-6e03610405ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LADOM'])[2]/preceding::a[1]</value>
      <webElementGuid>e5235b25-d7bc-4ac0-9687-c52df5cdc214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nous connaître'])[1]/preceding::a[1]</value>
      <webElementGuid>62957723-61b8-4bb0-b8df-3cdf208c300e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LADOM']/parent::*</value>
      <webElementGuid>a56efecc-6554-4164-9db6-2a844a134079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>a97e7576-735d-4e19-baeb-4fb7e5d77d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>77e1331a-5b4c-45ea-ad5e-193a1bb0b2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'LADOM' or . = 'LADOM')]</value>
      <webElementGuid>3aad4642-ba73-4a59-9386-9c776feb905b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
