<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Implantations</name>
   <tag></tag>
   <elementGuidId>628ac835-2109-4c21-bb45-255f9ec26d2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Nous rejoindre'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Implantations &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b5c06f5-0969-4f9d-ba8b-4e57db4b3444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ladom.fr/implantation/</value>
      <webElementGuid>16668818-8023-4689-af0d-8a294d164344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Implantations</value>
      <webElementGuid>ce46362e-20ea-418a-9d9c-ed1b21827ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between text-lg leading-6 pb-2 border-b border-transparent hover:border-white</value>
      <webElementGuid>10e9b0e3-c376-4473-9abd-3c200e6052c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Implantations</value>
      <webElementGuid>2c0956fe-74d4-46e6-b45d-61548226c621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;hidden lg:flex justify-end items-center flew-row w-full relative px-4 py-6 mb-4&quot;]/div[@class=&quot;group&quot;]/div[@class=&quot;hidden group-hover:flex bg-ladom-gray text-white absolute top-16 left-0 right-0 py-12 z-10 mx-4&quot;]/div[@class=&quot;w-1/4 flex flex-col&quot;]/div[@class=&quot;py-2 me-8&quot;]/a[@class=&quot;flex justify-between text-lg leading-6 pb-2 border-b border-transparent hover:border-white&quot;]</value>
      <webElementGuid>11378957-8af6-4bbb-be86-e53875d89bc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nous rejoindre'])[1]/following::a[1]</value>
      <webElementGuid>154b0d15-901f-4210-bfdf-c590b8e4550a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partenaires'])[1]/following::a[1]</value>
      <webElementGuid>7fb2b8ae-a8c4-4233-b164-df85d90d2138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Politique RH'])[1]/preceding::a[1]</value>
      <webElementGuid>01be645a-3150-4b2c-9efe-a08f174344e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ladom.fr/implantation/')]</value>
      <webElementGuid>0849fe4c-e0e3-4e24-9831-df4848e19f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>f1b8c331-4d25-4746-b5fc-c080415ec459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ladom.fr/implantation/' and @title = 'Implantations' and (text() = 'Implantations' or . = 'Implantations')]</value>
      <webElementGuid>7b6c52f7-46f4-4c84-b0a0-0531d24e1c96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
