<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Organisation</name>
   <tag></tag>
   <elementGuidId>98ce4182-d5dd-4521-97be-acfac9fb05c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Mission'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Organisation &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7e4c973-b187-486b-a788-931f30dba905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ladom.fr/nous-connaitre/notre-organisation/</value>
      <webElementGuid>d6efa6c0-fbc1-42da-b68b-8c0bd13be08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Organisation</value>
      <webElementGuid>0dc39127-f3f9-4e74-9bac-093f1c3a18dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between text-lg leading-6 pb-2 border-b border-transparent hover:border-white</value>
      <webElementGuid>23d3313b-51ff-4a96-8c09-5a7405f8e74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Organisation</value>
      <webElementGuid>c2e01442-e6f8-4179-b089-e88f52e78974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;hidden lg:flex justify-end items-center flew-row w-full relative px-4 py-6 mb-4&quot;]/div[@class=&quot;group&quot;]/div[@class=&quot;hidden group-hover:flex bg-ladom-gray text-white absolute top-16 left-0 right-0 py-12 z-10 mx-4&quot;]/div[@class=&quot;w-1/4 flex flex-col&quot;]/div[@class=&quot;py-2 me-8&quot;]/a[@class=&quot;flex justify-between text-lg leading-6 pb-2 border-b border-transparent hover:border-white&quot;]</value>
      <webElementGuid>d4374511-6472-48ed-82e5-ade156738a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mission'])[1]/following::a[1]</value>
      <webElementGuid>308a755d-c615-480e-aeed-fdfb53c1fca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nous connaître'])[1]/following::a[2]</value>
      <webElementGuid>6929607c-c788-4f7e-8dac-6db70748be86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publications'])[1]/preceding::a[1]</value>
      <webElementGuid>127baef4-b8ab-48c6-a525-094f70c16e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ladom.fr/nous-connaitre/notre-organisation/')]</value>
      <webElementGuid>c2eb0aa9-f00c-4147-9f3a-3d61c245d253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div[3]/a</value>
      <webElementGuid>18c3280f-ac34-44df-bdad-6b2d0951efc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ladom.fr/nous-connaitre/notre-organisation/' and @title = 'Organisation' and (text() = 'Organisation' or . = 'Organisation')]</value>
      <webElementGuid>985fd564-0816-40b6-be1d-766f03710af8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
