<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Partenaires</name>
   <tag></tag>
   <elementGuidId>3f9c4721-5b11-44fd-b3ed-911a01df08b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Publications'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Partenaires &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54bcaa67-cc32-4d1b-93b4-e471881047aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ladom.fr/partenaire/</value>
      <webElementGuid>a3bec447-8d9e-44a2-9c46-840c25bdd212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Partenaires</value>
      <webElementGuid>d25e2a19-bc7b-4b4f-8ef9-2019b2815dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between text-lg leading-6 pb-2 border-b border-transparent hover:border-white</value>
      <webElementGuid>cc37e1cd-59db-4119-bb93-7e6a7fa823ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Partenaires</value>
      <webElementGuid>dadb8cbd-3e99-41a8-8079-c7f10a182dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;hidden lg:flex justify-end items-center flew-row w-full relative px-4 py-6 mb-4&quot;]/div[@class=&quot;group&quot;]/div[@class=&quot;hidden group-hover:flex bg-ladom-gray text-white absolute top-16 left-0 right-0 py-12 z-10 mx-4&quot;]/div[@class=&quot;w-1/4 flex flex-col&quot;]/div[@class=&quot;py-2 me-8&quot;]/a[@class=&quot;flex justify-between text-lg leading-6 pb-2 border-b border-transparent hover:border-white&quot;]</value>
      <webElementGuid>252e74e3-896c-4a9e-9f86-5a585ad508ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publications'])[1]/following::a[1]</value>
      <webElementGuid>04fe7c91-df21-4f33-8ff7-487816cf86bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organisation'])[1]/following::a[2]</value>
      <webElementGuid>57f6b79d-ff09-490e-ae93-0a034c4b09b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nous rejoindre'])[1]/preceding::a[1]</value>
      <webElementGuid>6702a022-69a8-4646-9e47-b42570610d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ladom.fr/partenaire/')]</value>
      <webElementGuid>b101d510-d355-4c09-8d34-87a3dfae5da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div[5]/a</value>
      <webElementGuid>9ad3b69e-b5c3-418a-b16e-4775c18ea9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ladom.fr/partenaire/' and @title = 'Partenaires' and (text() = 'Partenaires' or . = 'Partenaires')]</value>
      <webElementGuid>30dbca54-efe6-4447-b47c-38d9294ac307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
