<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Publications</name>
   <tag></tag>
   <elementGuidId>bcc4505b-b407-4260-bd5f-336c548d632b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Organisation'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Publications &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0db3119f-18fc-43ca-a10c-3070e3f3643b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ladom.fr/nos-publications/</value>
      <webElementGuid>ba983f9d-bddb-4684-a2ee-c5da54fc94e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Publications</value>
      <webElementGuid>b6d23c41-7fac-4286-8830-9a566dd048ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between text-lg leading-6 pb-2 border-b border-transparent hover:border-white</value>
      <webElementGuid>08979837-3a06-4a4e-ac44-15742db57450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publications</value>
      <webElementGuid>4c806da8-4765-4ac8-b759-129f9459cef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;hidden lg:flex justify-end items-center flew-row w-full relative px-4 py-6 mb-4&quot;]/div[@class=&quot;group&quot;]/div[@class=&quot;hidden group-hover:flex bg-ladom-gray text-white absolute top-16 left-0 right-0 py-12 z-10 mx-4&quot;]/div[@class=&quot;w-1/4 flex flex-col&quot;]/div[@class=&quot;py-2 me-8&quot;]/a[@class=&quot;flex justify-between text-lg leading-6 pb-2 border-b border-transparent hover:border-white&quot;]</value>
      <webElementGuid>11562717-d304-4250-ad6c-52581b5a9aea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organisation'])[1]/following::a[1]</value>
      <webElementGuid>cc1fce3b-e300-4345-871f-f7655bcac759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mission'])[1]/following::a[2]</value>
      <webElementGuid>d3076374-eb93-41ab-881a-9b005a995bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partenaires'])[1]/preceding::a[1]</value>
      <webElementGuid>2f380cc3-124b-4cbc-9ea8-b37891403e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ladom.fr/nos-publications/')]</value>
      <webElementGuid>c90b066c-d584-4742-a9ce-0f7d0c7d1a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div[4]/a</value>
      <webElementGuid>10c64880-fcf9-45f6-9839-d4a44931b122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ladom.fr/nos-publications/' and @title = 'Publications' and (text() = 'Publications' or . = 'Publications')]</value>
      <webElementGuid>3bddc821-5680-4942-86f1-6313a41ba3a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
